name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Elixir
        uses: actions/setup-elixir@v1
        with:
          elixir-version: 1.10

      - name: Install dependencies
        run: mix deps.get

      - name: Run tests
        run: mix test
